### ISSUE TITLE
请求增加功能：在工具栏中显示/隐藏

### ISSUE THREAD

**Issue by sanmaodo** [hankxdev/one-click-extensions-manager#101]
每次安装扩展时，工具栏图标都被默认隐藏，需要手动设置显示，这很烦人。
如果 [one-click-extensions-manager] 可以直接操作，那就太好了。
比如下图这个样子：
![image](https://user-images.githubusercontent.com/29154707/225685668-bd669cae-28fe-4b95-b144-3e666591ffc2.png)

**Comment by fregante** [comment]
Duplicate of https://github.com/hankxdev/one-click-extensions-manager/issues/32

**Comment by sanmaodo** [comment]
@fregante 谢谢你的回复，希望没有打扰到你，我请求增加的功能是指edge自带的 [show in toolbar]
![88273b190b5da46c5cb47a897b19ba2](https://user-images.githubusercontent.com/29154707/225697909-df0bca6d-c2e2-4aa2-bf50-cd47ed85c09e.png)

**Comment by fregante** [comment]
Oh I had misunderstood the translation. 

Unfortunately there is no API to do change the pinned (`isOnToolbar`) status: https://developer.chrome.com/docs/extensions/reference/management/

**Comment by sanmaodo** [comment]
@fregante 谢谢！我会继续等待。

**Comment by hankxdev** [comment]
@sanmaodo 是的，目前Chrome 和 Edge都没有支持此功能的API。

**Comment by sanmaodo** [comment]
@hankxdev 是的，我已知晓，也许以后会有 ：)
