### ISSUE TITLE
The options icons are shown by default

### ISSUE THREAD

**Issue by hankxdev** [hankxdev/one-click-extensions-manager#113]
Version: 23.5.11
- click the icon
- show the popup
- the options icons(delete, chrome web store, etc.) are shown, they should be hidden by default.

<img width="428" alt="Screenshot 2023-07-26 at 20 26 00" src="https://github.com/hankxdev/one-click-extensions-manager/assets/3389447/db562ea3-5112-4932-b467-465e67902631">

**Comment by fregante** [comment]
Did you change your options?

<img width="281" alt="Screenshot" src="https://github.com/hankxdev/one-click-extensions-manager/assets/1402241/78bee017-bfca-4208-8ade-f5f958fe959c">

**Comment by hankxdev** [comment]
Hmm, this is weird. I don't remember that I changed it. But it seems that mine is shown by default 😅  False alarm, sorry.
