### ISSUE TITLE
mac上，点击删除没有任何反应

### ISSUE THREAD

**Issue by 1xiaocainiao** [hankxdev/one-click-extensions-manager#114]
感谢提供这么好的扩展，使用中发现一个问题，如下

在mac  Ventura , chrome 115.0.5790.170 arm，点击删除没有任何反应，
希望能增加同步配置功能

**Comment by hankxdev** [comment]
- 刚在同版本Mac，Chrome 117 中尝试了删除没有问题。点击删除后会弹出默认删除确认对话框，如下图，你看一下是不是你多屏导致弹出的删除框去了别的地方没打开。这个功能从来没改过，所以不太会出问题。
<img width="380" alt="Screenshot 2023-08-04 at 14 01 20" src="https://github.com/hankxdev/one-click-extensions-manager/assets/3389447/96903bd1-4f37-442d-8daa-e4d7566e843a">

- 配置是默认同步的，使用的Chrome的storage.sync API。 根据文档，此同步功能需要你使用相同账户登录Chrome才会起作用。
> If syncing is enabled, the data is synced to any Chrome browser that the user is logged into. If disabled, it behaves like storage.local. Chrome stores the data locally when the browser is offline and resumes syncing when it's back online. The quota limitation is approximately 100 KB, 8 KB per item. Consider using it to preserve user settings across synced browsers.

**Comment by 1xiaocainiao** [comment]
感谢回复，确实是自己开太多窗口导致的问题，不好意思
