### ISSUE TITLE
[Feature request] Add favorite/pin extension feature

### ISSUE THREAD

**Issue by inson1** [hankxdev/one-click-extensions-manager#118]
I also want #81 
Without that I cant use it. Cant you just set it as option in setting? Please?

**Comment by fregante** [comment]
Duplicate of https://github.com/hankxdev/one-click-extensions-manager/issues/81

**Comment by fregante** [comment]
That issue was locked, that means we do not need your "me too" comment. 

> Without that I cant use it.

If you don't want to use this extension, don't use it.
