### ISSUE TITLE
Chrome Web Store upload workflow broken

### ISSUE THREAD

**Issue by fregante** [hankxdev/one-click-extensions-manager#132]
I think the token is expired:

```
npm warn exec The following package was not found and will be installed: chrome-webstore-upload-cli@3.3.0
- Fetching token
Error: Bad Request
    at throwIfNotOk (file:///home/runner/.npm/_npx/da388c0a4eab99e8/node_modules/chrome-webstore-upload/index.js:27:23)
    at APIClient.fetchToken (file:///home/runner/.npm/_npx/da388c0a4eab99e8/node_modules/chrome-webstore-upload/index.js:123:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async doAutoPublish (file:///home/runner/.npm/_npx/da388c0a4eab99e8/node_modules/chrome-webstore-upload-cli/cli.js:75:19)
    at async init (file:///home/runner/.npm/_npx/da388c0a4eab99e8/node_modules/chrome-webstore-upload-cli/cli.js:173:9)
    at async file:///home/runner/.npm/_npx/da388c0a4eab99e8/node_modules/chrome-webstore-upload-cli/cli.js:182:5 {
  response: undefined
}
```

Can you follow this guide and set the secrets in the repo settings again?

https://github.com/fregante/chrome-webstore-upload-keys

**Comment by fregante** [comment]
For now I uploaded the extension manually and also updated the description:

```
Open-source extension to toggle your extensions.

"One Click Extensions Manager" is intentionally very simple, it's only meant to let you toggle extensions on and off. If you need a full-featured extension manager, this isn't it.

Full list of features:

- List the installed extension in a popup
- Search the list of extensions
- Navigate the list via keyboard shortcuts
- Toggle extensions on and off
- Toggle all extensions at once
- Uninstall extensions
- Visit the options and homepage of each extension
- Undo/redo any changes (temporarily)

Also:

- Completely open source on GitHub
- No ads
- No data collection
- No superfluous features
- Well-maintained since 2017
```

**Comment by hankxdev** [comment]
```
Well-maintained since 2017
```

you saw those comments too, hah? 🤣

**Comment by fregante** [comment]
> ```
> Well-maintained since 2017
> ```
> 
> you saw those comments too, hah? 🤣

Which comments? 🤔 

I wrote that because it's old, we fix things quickly, we update at least once a year, we respond to all messages here 😃

**Comment by hankxdev** [comment]
The latest comments it gets say it is outdated anymore lol. I was too lazy to respond in the store. Some guy even spam it several months ago.

**Comment by fregante** [comment]
You can just reply "If you encounter bugs, please open an issue on the GitHub repo. The extension works correctly in all the browsers I tested"

**Comment by hankxdev** [comment]
just created a new credential in GCP and updated the action secrets

**Comment by fregante** [comment]
🙌 great!

I suppose after https://github.com/hankxdev/one-click-extensions-manager/issues/134 we can trigger a new release to test it out

**Comment by fregante** [comment]
> Some guy even spam it several months ago.

Oh I just saw that review. Crazy how people get so pissed at absolutely nothing. 🤷‍♂️

**Comment by fregante** [comment]
It looks like I can't reply to them if a developer already answered. I was going to post something that can help others, rather than replying to the specific user:

> The extension has been working well for 30000 users. If you encounter issues, please open an issue on our GitHub repo and we can look into it.

and

> There has never been a single report of "lag" on our GitHub repo so that's clearly a lie. I don't understand what this extension has done to you to cause so much trouble in your life. This extension is extremely simple and we never claim otherwise. If you're looking for more options, use a different extension.


Do you mind if I reply directly?

**Comment by hankxdev** [comment]
no problem. just do it :)

**Comment by fregante** [comment]
It won't let me if your answer is there, just one reply is allowed

**Comment by hankxdev** [comment]
that's a crazy person. he keeps deleting and posting reviews. I think we better just ignore it. 
<img width="503" alt="image" src="https://github.com/user-attachments/assets/2b760310-e9e6-4150-8539-1ea0bd5189d6">

**Comment by fregante** [comment]
I don’t think he's actually deleting and posting again, but just editing and tweaking word by word. I invited him to open an issue but yeah, hopefully he'll just get a life after this.

**Comment by hankxdev** [comment]
he IS deleting and post again, that's why my reply was not there, I did not delete my reply :)

**Comment by fregante** [comment]
Generally the response is lost when the review is changed. The same happens on Google Maps
