### ISSUE TITLE
Update version on Edge store

### ISSUE THREAD

**Issue by fregante** [hankxdev/one-click-extensions-manager#133]
It's a little out of date: https://microsoftedge.microsoft.com/addons/detail/one-click-extensions-mana/jdodenbllldnoogfmbmmgpieafbnaogm

This is why I didn't want to publish it there before, because the upload hasn't been automated.

You can download the latest from the assets on the release:

https://github.com/hankxdev/one-click-extensions-manager/releases/tag/24.7.18

**Comment by hankxdev** [comment]
yeah, I saw Edge now also has an [API](https://learn.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/api/using-addons-api) . maybe we can automate it as well

**Comment by fregante** [comment]
> maybe we can automate it as well

The API exists: https://learn.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/api/using-addons-api#using-the-api-endpoints

But I don't see any CLIs on npm. I don't personally support the Edge store so it's up to you if you want to set that up. Given the frequency of updates it might just be easier for you to upload new releases when you get a notification

**Comment by fregante** [comment]
I see it now 🙌
