### ISSUE TITLE
Update list on global events

### ISSUE THREAD

**Issue by fregante** [hankxdev/one-click-extensions-manager#134]
https://developer.chrome.com/docs/extensions/reference/api/management#event

- [x] Uninstalled: https://github.com/hankxdev/one-click-extensions-manager/blob/14ee1e5ddc946b82c504f1c5e7e7f8ab8d6f0663/source/app.svelte#L101-L104
- [ ] Installed
- [ ] Enabled (outside this extension)
- [ ] Disabled (outside this extension)

"installed" is easy to add. Enabled/disabled events mean also removing the state changes from the svelte app, i.e. this line: https://github.com/hankxdev/one-click-extensions-manager/blob/14ee1e5ddc946b82c504f1c5e7e7f8ab8d6f0663/source/app.svelte#L75

**Comment by hankxdev** [comment]
i'm a little bit confused, doesn't the extension list refresh whenever the user opens the manager popup? so when a user installs/uninstalls/enables/disables an extension from outside the manager, the list should be refreshed when they open the manager.

unless they keep the manager open, and do these actions in another window. which is a very rare scenario.

**Comment by fregante** [comment]
It doesn't because those listeners are missing. We only have onUninstalled. 

You verify by opening the extension in a tab or popup, then install a new one. Or toggle one via the native manager

**Comment by hankxdev** [comment]
yeah, I mean, it happens only if you keep the manager open and then do these actions. 

I personally never open the manager in a tab or popup window. but you are right, if someone is doing so, we can add these listeners.
