### ISSUE TITLE
Profile Support

### ISSUE THREAD

**Issue by gringoloc0** [hankxdev/one-click-extensions-manager#145]
"Please don't suggest adding sorting, grouping, and options.
There are already plenty of ugly managers with all of that."...Would be valid if you have minimal extensions; However, when you have dozens lack of grouping is unmanageable, so...You COULD suggest other tools, OR, you could listen to people who use your product...Seems pretty simple to me....

**Comment by fregante** [comment]
This is not a product, it's a free extension. I don't come to your house and expect you to feed me steak. What kind of reasoning is that?

You like it? Use it. Don't like it? Find something else or build it.

**Comment by fregante** [comment]
Here, this extension looks good and has groups. We can't guarantee its safety though: https://chromewebstore.google.com/detail/extentie-extension-manage/bhjkadebkpcekfbjkkmcjhhlfidajfmi
