### ISSUE TITLE
Update descriptions in other languages on web store

### ISSUE THREAD

**Issue by fregante** [hankxdev/one-click-extensions-manager#148]
I just found out that each localization has its own store description, and they're all stuck probably to whatever description was available when the language was added. See for example:

- IT: (2017?) https://chromewebstore.google.com/detail/one-click-extensions-mana/pbgjpgbpljobkekbhnnmlikbbfhbhmem?hl=it
- TW: (2019) https://chromewebstore.google.com/detail/快捷擴展管理/pbgjpgbpljobkekbhnnmlikbbfhbhmem?hl=zh_tw
- CN (2016): https://chromewebstore.google.com/detail/快捷扩展管理/pbgjpgbpljobkekbhnnmlikbbfhbhmem?hl=zh_cn

Once the current update (#138)  is reviewed, I'll go through and empty all descriptions except the Chinese ones.

**Comment by fregante** [comment]
<img width="948" alt="Screenshot" src="https://github.com/user-attachments/assets/4f4af52d-ea65-48be-8837-430506e7a8d3">

**Comment by fregante** [comment]
Done:

- Emptied all descriptions except English and 2 Chinese
- Added an Italian version (partially translated via ChatGPT)
- Added rice

Missing:

- [ ] Ensure that other languages still show the English version
- [ ] Update the 2 Chinese versions

**Comment by hankxdev** [comment]
@fregante done for 2 Chinese versions
notes
- removed 'if you are looking for .....' in the first line due to different culture :) 
- the extension got better after you worked on it since 2017, however, before that, I also designed and maintained it since I can not remember when, so I changed 2017 to 2016 :D
