### ISSUE TITLE
Update screenshot and description in the Edge Store

### ISSUE THREAD

**Issue by fregante** [hankxdev/one-click-extensions-manager#149]
You can take them from https://github.com/hankxdev/one-click-extensions-manager/issues/138, but you might have to scale them down. I don't know how strict the Edge store is.

In the order shown on https://chromewebstore.google.com/detail/one-click-extensions-mana/pbgjpgbpljobkekbhnnmlikbbfhbhmem?hl=en

Store link: https://microsoftedge.microsoft.com/addons/detail/one-click-extensions-mana/jdodenbllldnoogfmbmmgpieafbnaogm

Description:

```
"One Click Extensions Manager" is intentionally very simple, it's only meant to let you toggle extensions on and off. If you need a full-featured extension manager, this isn't it.

Full list of features:

- List installed extension in a popup or in the sidebar
- Search/filter extensions
- Keyboard shortcuts
- Toggle extensions on and off
- Toggle all extensions at once
- Uninstall extensions
- Visit the options and homepage of each extension
- Undo/redo any changes (temporarily)

Also:

- Completely open source on GitHub
- No ads
- No data collection
- No superfluous features
- Well-maintained since 2017

Please open an issue on GitHub if you encounter bugs.

Repository: https://github.com/hankxdev/one-click-extensions-manager

Made with 🍚 in Italy and China
```

**Comment by fregante** [comment]
@hankxdev it would be a a good time to update the version and screenshot now.

Zip: https://github.com/hankxdev/one-click-extensions-manager/releases/tag/24.9.29

Screenshots: https://github.com/hankxdev/one-click-extensions-manager/issues/138

**Comment by fregante** [comment]
The screenshots are missing there. Did they remove it because they're not based on Edge? The description is also still the same

**Comment by hankxdev** [comment]
updated English description and added screenshots
