### ISSUE TITLE
Add an option to turn off auto-trim extension names

### ISSUE THREAD

**Issue by Bearkshi** [hankxdev/one-click-extensions-manager#156]
Some extension names contain '-', e.g. 'User-Agent Switcher and Manager' , 'enhanced-h264ify'.
Auto-trim extension names will cause some extensions with similar names to be indistinguishable. It would be nice to have an option to turn this feature off, thank you!

**Comment by hankxdev** [comment]
I think we should make auto trim name as an optional feature and make it off by default.

**Comment by fregante** [comment]
The behavior you described is actually a bug, so let me fix that first. It should not trim everything after `User-` obviously
