### ISSUE TITLE
Get rid of the error and warning messages that flooding the console

### ISSUE THREAD

**Issue by hankxdev** [hankxdev/one-click-extensions-manager#158]
<img width="803" alt="Screenshot 2024-09-27 at 11 34 04" src="https://github.com/user-attachments/assets/07516a9a-938d-4b0d-848b-f092f9f8811e">

- for the warnings, I think we can simply pass `extension` to the Extension component, and then spread the props that we need there
- for the error, we need to find another way to make sure there will be only 1 window open.

**Comment by fregante** [comment]
I don’t think this is a problem, the warnings are just from Svelte, they don’t cause any issues. 

As for the error, there’s no other way, I can also just add a `try/catch` to silence it

**Comment by hankxdev** [comment]
yeah, the warnings don't cause any issues. just annoying while debugging :).

I was trying to fix this but you are faster 😄
