### ISSUE TITLE
Unable to "undo/redo"

### ISSUE THREAD

**Issue by jvthomas90** [hankxdev/one-click-extensions-manager#163]
What it says on the tin, basically.

I mean, if I type something in the input box then undo/redo operations work on the text field, obviously. But I'm no longer able to un/toggle extensions back and forth from an in/active state as it was once possible to do and the description text at the top explicitly gives instructions for. 

I'm unsure of how long this has been the case as I haven't felt the need to utilize this extension for a while now and I've noticed several updates have since been pushed to it during that time _(awesome idea introducing a sidebar view, btw! I'm still partial to the pop-out window but I'm happy to see this new inclusion nonetheless:)_ any of which could've been responsible for this "breaking" change.

Being able to easily backtrack on changes is pretty much one of the key defining differentiators of this extension manager when compared to all others, so I'm sad to see it go... on the other hand, the fact that the description/instruction text at the top still explicitly states that undo/redo operations are possible makes me think this must've been a simple mistake that caused this regression in behavior.

I don't know what other details I can add or what steps I can share to reproduce this bug, I just noticed it and noticed no one else seemed to report on it since the last update (which was like 2 or 3 months ago apparently) so I felt I needed to share my observation.

Of course, the fact that no one else logged this issue could also mean that there isn't in-fact anything wrong with the extension and it's something unique about my current config or setup that's wonky. But... I'm honestly uncertain how that could be the case. I'm not on an outdated version of Chrome. I've tried various other extension settings too and this problem still persists whether I'm using the tab view, the sidebar view or the original pop-up view too.

But if there's anything I'm missing, feel free to point me in the right direction for a fix. Til then, I have to assume that it's the extension that's changed in some manner

**Comment by fregante** [comment]
Just to double-check: are you using the standard Google Chrome?

**Comment by jvthomas90** [comment]
Yep, I'm on the stable release.

Can confirm this problem exists when I use my installation of the Edge browser as well (which is also on the public/stable release channel)
