### ISSUE TITLE
Keyboard navigation

### ISSUE THREAD

**Issue by fregante** [hankxdev/one-click-extensions-manager#21]
up/down or tab should let the user navigate the list via keyboard

**Comment by HangYang** [comment]
was planned to implement it, will you do it?

**Comment by bfred-it** [comment]
I don't have much time at the moment, you can do it 👍

**Comment by bfred-it** [comment]
Hey I just realized that we live close now. 😄  Where in China do you live? I'm in Taiwan

**Comment by HangYang** [comment]
I'm in PRC mainland, Chengdu, Sichuan
https://www.google.com/maps/place/16+Ren+Min+Zhong+Lu+Yi+Duan,+LuoMaShi,+Qingyang+Qu,+Chengdu+Shi,+Sichuan+Sheng,+China,+610041/@30.6105922,104.1910616,12.5z/data=!4m5!3m4!1s0x36efc524cedeb82b:0xaaaf58e7a28b5528!8m2!3d30.6599904!4d104.0664268

**Comment by bfred-it** [comment]
Sichuan! 😍  I hope I can visit one day, Sichuan has the best Chinese food!

**Comment by HangYang** [comment]
yeah. it has 😆 . well if you come here, I could be your guide.

**Comment by bfred-it** [comment]
Perhaps it's worth rewriting the extension with [svelte](https://svelte.technology/). It's a lightweight alternative to React, it would handle updating the dom for us instead of fighting it with jQuery. I myself have only used it for a few hours, but it's not too difficult.

**Comment by HangYang** [comment]
Great idea, but it's near the end of year, too many works needs to be done for living.. so I have no time working on it for now and maybe this month.

**Comment by moshfeu** [comment]
Actually tab does navigate (although it also focus on the "gear" icon which I believe it's good).
IMHO, the `outline` reset styles can be removed (double negative 😀). Although "reset" the default styles is common, leave it with nothing it makes navigation with kb harder.

https://github.com/hankxdev/one-click-extensions-manager/blob/03dca4c0f5289cf446b42282714e132e58a2b1b9/src/popup.css#L12

https://github.com/hankxdev/one-click-extensions-manager/blob/03dca4c0f5289cf446b42282714e132e58a2b1b9/src/popup.css#L53

**Comment by moshfeu** [comment]
Removing outline will not impact the regular state. Only when a button becomes "active" which can be caused either by tab or click. Either way, Chrome improved the "active" style so now it looks pretty good.

![Screen Shot 2020-04-07 at 23 29 26](https://user-images.githubusercontent.com/3723951/78716507-aa88d100-7927-11ea-8387-86199b56062e.png)
![Screen Shot 2020-04-07 at 23 29 36](https://user-images.githubusercontent.com/3723951/78716522-af4d8500-7927-11ea-9fbe-e5eb0e8589e1.png)

**Comment by fregante** [comment]
> Only when a button becomes "active" which can be caused either by tab or click

Yeah, that's pretty ugly when using the mouse. The "add class on `tab`" behavior is preferred. Basically this: https://github.com/ten1seven/what-input#basic-styling

**Comment by moshfeu** [comment]
So basically, once the class was added, it won't be removed..

**Comment by fregante** [comment]
Now it works with <kbd>tab</kbd>
