### ISSUE TITLE
Hide extensions that are used often

### ISSUE THREAD

**Issue by yunxiaoxiao11** [hankxdev/one-click-extensions-manager#36]
some extensions are often used, in other words, these extensions always use, if they can be hidden, the list will be more concise.

**Comment by fregante** [comment]
What do you mean by “used”? All enabled extensions are technically “in use”

**Comment by hankxdev** [comment]
I think he meant those extensions that user always in use and never want to disable.

**Comment by fregante** [comment]
That'd require additional UI to pick which extensions are "often used". There are plenty other extension that have lists and groups for this use, this extension doesn't have to become another one of those.
