### ISSUE TITLE
icon still misaligned on master

### ISSUE THREAD

**Issue by hankxdev** [hankxdev/one-click-extensions-manager#37]
<img width="136" alt="Screen Shot 2020-03-17 at 7 48 14 PM" src="https://user-images.githubusercontent.com/3389447/76853547-75d5ac80-6888-11ea-8a3c-a47d4cc01650.png">

**Comment by hankxdev** [comment]
@fregante not sure what's your commits on master for, but the icon still misaligned

**Comment by fregante** [comment]
The alignment is still made under your PR. The commits on master are for the other changes you made and other small fixes
