### ISSUE TITLE
Add dark theme

### ISSUE THREAD

**Issue by darkred** [hankxdev/one-click-extensions-manager#38]
I've just found the extension and I love it! Great, compact and so convenient! Thanks a lot!

I'd like to make some suggestions, plase:
(using Chrome in win10)

- optional **dark theme** in the popup
- to be able to display the extensions **sorted by last update date**,
What I have in mind is: adding in the popup (after `DISABLE ALL` and `ENABLE ALL`) a `Last Updated` button that would toggle between: 
    - displaying all extensions (=without enabled/disabled grouping) sorted by last updated date
    - the current display, i.e. alphabetically with enabled/disabled grouping.
- **hovering** on each entry on the list to also display as tooltip the extension's **version + last update date** (currently it only displays the extension name)

Thank you

**Comment by fregante** [comment]
> - optional dark theme in the popup

This is fine, the rest isn't. There are plenty of other extensions with all sorts of filters and sorting options. This doesn't have to become like them.

**Comment by darkred** [comment]
Thank you very much!
