### ISSUE TITLE
Feature: Sort extensions by most usage

### ISSUE THREAD

**Issue by moshfeu** [hankxdev/one-click-extensions-manager#49]
It will be great to have the most interacted extensions on top, after the active extensions of course.
"most interacted" are the extensions that the user toggle on / off the most?

**Why?**
Let's say a user installed an extensions called "aa" but they use it once a month (so in the rest of the time, they disable the extension". They also installed "qa" extension and they use it one a week. 
It will be much easier to find it if it will be above "aa" in the list.

**How?**
Probably can be stored in [storage](https://developer.chrome.com/extensions/storage).
A "sort by" dropdown can be added to the UI to allow both of the sorts (the value also will stored in storage).

**Comment by fregante** [comment]
This extension is to be considered feature-complete. There are plenty other extensions with all kinds of grouping, sorting, filtering and complex UI. 

This extension is good because it’s simple. The more “just this one button” the less simple it will be.
