### ISSUE TITLE
Please reconsider adding categories

### ISSUE THREAD

**Issue by klarezz** [hankxdev/one-click-extensions-manager#55]
Thanks for this promising extension.

If I may, it would really be great to have categories (or grouping) at least.

I'm still using [extensions-manager](https://chrome.google.com/webstore/detail/extensions-manager-aka-sw/lpleipinonnoibneeejgjnoeekmbopbc) because the categories feature is awesome. It seems broken however: new categories can't be created unless imported via a configuration file.

It would be great if you could take some time to reconsider adding a categories feature.

**Comment by fregante** [comment]
Duplicate of https://github.com/hankxdev/one-click-extensions-manager/issues/27
