### ISSUE TITLE
A button for activating extension on the page

### ISSUE THREAD

**Issue by ni554n** [hankxdev/one-click-extensions-manager#58]
I love the simplicity of this extension. It has everything I want from an extension manager.

But you need to open Chrome Extensions menu if you want to activate an extension on the page. Is it possible to add an "Activate Extension" button so that I can finally stop using Chrome's default Extension menu for this task.

**Comment by fregante** [comment]
Interesting, but I don’t think it’s possible

**Comment by snowman** [comment]
If you have 100 or more chrome extensions, is too hard to activate the extension on the current page.

and the bad news is Chrome doesn't have an API to do that.

I think Chrome should add a built-in search control under collapsed extensions to filter extensions.

**Comment by fregante** [comment]
This is not a Chrome forum, we can't do anything with such suggestions 😅
