### ISSUE TITLE
The second-to-last Release action failed with error code 400 (Bad Request)

### ISSUE THREAD

**Issue by darkred** [hankxdev/one-click-extensions-manager#62]
The [second-to-last](https://github.com/hankxdev/one-click-extensions-manager/actions/runs/446609399) `Release` action run has failed, in particular the `Submit (chrome)` job failed as follows:

> Response code 400 (Bad Request)
>  "message": "Publish condition not met: To publish your item, you must certify that your data usage complies with our Developer Program Policies. You can certify this on the Privacy tab of the item edit page of the Developer Dashboard."

And, in the [last](https://github.com/hankxdev/one-click-extensions-manager/actions/runs/452838607) Release action, the 'Submit (chrome)' job was skipped.

Kindly cc @fregante as he is the one who manually triggered the action.

For reference, the latest version published in [CWS](https://chrome.google.com/webstore/detail/one-click-extensions-mana/pbgjpgbpljobkekbhnnmlikbbfhbhmem) is 20.9.9, while the latest release is [20.12.27](https://github.com/hankxdev/one-click-extensions-manager/releases/tag/20.12.27) .

P.S. Happy new year!

**Comment by fregante** [comment]
Thanks! I added the missing data and re-submitted it. Happy new year!

**Comment by darkred** [comment]
The new version is now in CWS. Thank you!

**Comment by darkred** [comment]
Hi @fregante 

I see that in [today](https://github.com/hankxdev/one-click-extensions-manager/actions/runs/3110766643)'s `Release` action run, the `Submit (chrome)` job failed:

>    "code": 400,
>    "message": "Publish condition not met: You must verify your contact email before you can publish any item. Begin the verification process on the Account tab.",

**Comment by fregante** [comment]
Check the open issue

**Comment by darkred** [comment]
Greetings @fregante 

I noticed that it occurred again [today](https://github.com/hankxdev/one-click-extensions-manager/actions/runs/10161785967/job/28101041263), with the following error:

> code: 400,
> message: 'Publish condition not met: To publish your item, you must provide mandatory privacy information in the new Developer Dashboard: https://chrome.google.com/webstore/devconsole. Click on your item from the home page and enter this information on the Privacy practices tab.',

**Comment by fregante** [comment]
How do you know? 😂 

But yes I had to explain the new permission: 

- https://github.com/hankxdev/one-click-extensions-manager/pull/140#discussion_r1695707227
