### ISSUE TITLE
Redesign the icon with some improvements

### ISSUE THREAD

**Issue by ni554n** [hankxdev/one-click-extensions-manager#63]
Because it is one of the five extensions I have pinned in the toolbar, I look at the icon all the time.
I had some ideas in my mind, so I made this:

<img width="368" alt="Chrome Dark" src="https://user-images.githubusercontent.com/2310552/103838583-a0af1c80-50b7-11eb-8037-068de88da079.png"><img width="368" alt="Chrome Light" src="https://user-images.githubusercontent.com/2310552/103838587-a278e000-50b7-11eb-9c1a-0385e42f3407.png">

The idea is that the multiple puzzle pieces represents this extension better, as its main feature is to work with multiple extensions. And I think it looks modern with this material green color that goes well with both light and dark mode.

Here are some of the color variations I tried:

<img width="50" alt="icon18" src="https://user-images.githubusercontent.com/2310552/103838417-31392d00-50b7-11eb-9436-4774925064e2.png">

Let me know if you like any of these.

**Comment by fregante** [comment]
Thanks! 1 and 2 look good but I don't particularly see the need to replace the [current](https://github.com/hankxdev/one-click-extensions-manager/blob/d375281c4432bdd0459d30598638829dff7eb653/source/logo.png) one (other than perhaps to recreate it to center it better).

Either way it's a pretty generic icon so I'm afraid that people wouldn't recognize it anymore (and that it'd be lost among the other [dozen extensions](https://chrome.google.com/webstore/search/extension%20manager?_category=extensions))

**Comment by ni554n** [comment]
Yeah, I see your point. But it's hard to make complex shapes look good at 18x18 pixel.

**Comment by hankxdev** [comment]
thanks @ni554n yeah, I think the No. 2 looks really great.

**Comment by ni554n** [comment]
I'm leaving the necessary files here for you to try the second variant. Let's see if you like it enough to replace the current one.

Here is the [browserAction manifest](https://developer.chrome.com/docs/extensions/reference/browserAction/#manifest) documentation and the icon files: [icons.zip](https://github.com/hankxdev/one-click-extensions-manager/files/5792030/icons.zip).

**Comment by fregante** [comment]
What do you think about remake the current one so that it's centered and pixel-aligned at 18px?

![](https://github.com/hankxdev/one-click-extensions-manager/blob/d375281c4432bdd0459d30598638829dff7eb653/source/logo.png?raw=true)
