### ISSUE TITLE
List extensions by permissions

### ISSUE THREAD

**Issue by infokiller** [hankxdev/one-click-extensions-manager#65]
Having many extensions installed increases the security risk and makes it harder to audit them, so it would be very useful for me to see the extensions listed by their permission.
Do you think this feature is sensible for your project, or should I fork?

BTW, the issue template mentions: 

> Please don't suggest adding sorting, grouping, and options. 
> There are already plenty of ugly managers with all of that". 

What extensions are you referring to? 
I couldn't find many OSS extensions for managing other extensions (OSS is a must for me because of the sensitive permission this extension gets), so if you can list the ones you know, it would be great, as I'm reviewing prior work to find which one is the best for me.

Thanks!

**Comment by hankxdev** [comment]
I think it'd make the extension not as simple as it is now. 

but if you can suggest some design for this idea, might worth a try.

**Comment by infokiller** [comment]
This is the prototype I developed, using `<details>` to hide it by default:

![image](https://user-images.githubusercontent.com/10516814/112722090-8cd9c080-8f18-11eb-8621-4eae14e21da8.png)

And when it's opened:

![image](https://user-images.githubusercontent.com/10516814/112722103-97945580-8f18-11eb-9765-180f931db048.png)

**Comment by fregante** [comment]
I like the idea, but it’s a completely different purpose of what this extension is for: analyzing extensions once vs toggling extensions every day.

It’s tempting to add a secondary “report” that just shows the extension by permission but then this opens up the door to filtering and I don’t want to deal with that.
