### ISSUE TITLE
Please support keyboard shortcuts

### ISSUE THREAD

**Issue by Alphabet1226** [hankxdev/one-click-extensions-manager#70]
After I tried tons of extension managers, there is no doubt that this is the best one. 
It would be better if you could add the keyboard shortcuts!

**Comment by fregante** [comment]
What shortcuts would you like? The extension is already usable via keyboard

**Comment by hankxdev** [comment]
I think what they want is the hotkey to open the extension popup

**Comment by Alphabet1226** [comment]
> I think what they want is the hotkey to open the extension popup

Yeah, that's right, I just want a hotkey to open the extension.
![image](https://user-images.githubusercontent.com/51783873/128309665-3a89b330-8c5b-412b-8a3d-cb88ad17bc73.png)
