### ISSUE TITLE
The manifest version 3 causes bug

### ISSUE THREAD

**Issue by hankxdev** [hankxdev/one-click-extensions-manager#72]
In order to fix the hotkey issue that causes by manifest version 3, reverted to manifest version 2 with https://github.com/hankxdev/one-click-extensions-manager/commit/81e6f221e2edd15a211c44b7a05861769b51460d

however, it causes the extension to load an empty popup. to fix this issue, I reverted the above change.

Seems we need to do more to fix the hotkey issue.

**Comment by fregante** [comment]
Let's just leave it as it is. It works, people have to reload the extension after setting the key. We know this now

**Comment by hankxdev** [comment]
Great
