### ISSUE TITLE
Ability to access the extension popup menu from inside the extension manager

### ISSUE THREAD

**Issue by Droyk** [hankxdev/one-click-extensions-manager#73]
Ability to access the extension popup menu (that gets enabled when the user clicks the extension badge with the Left Mouse button e.g. the ublock origin popup) from inside the extension manager.

Since I don't like too many extensions taking space on my toolbar or address bar. So I hide them however often I need to configure the extension options in the popup menu. so I have to make them visible again to see the popup options! it would be great if the user can activate the popup directly from the manager! since the Left mouse button is used for one-click enable/disable.

you can add a middle mouse button to activate the popup or just add another option-button to activate the popup like when the user right-clicks the extension three options become available to the user. you can add another button there to open the popup or just make it visible all the time. like you are doing it for the options page. hide that options page button in the right-click menu & keep the popup button visible all the time. or everything stays the same and you can show the popup when the user clicks the extension badge (Icon) in the manager and enable/disable it when the user hits the name of the extension. 
e.g. to enable the ublock origin popup from your extension manager. I just need to click on the badge of ublock origin and if I want to enable/disable it. I just need to click on the name of the extension. simple!

**Comment by fregante** [comment]
Unfortunately this is not possible. The only way you can access that menu is by clicking on the browser's icon or by setting a shortcut in the chrome://extensions page. This extension just does not have access to any of that.

**Comment by fregante** [comment]
It would be "Activate the extension"

https://obie.ai/blog/how-to-add-and-remove-custom-keyboard-shortcuts-and-hotkeys-for-a-chrome-extension-in-5-seconds-flat/

I'm not entirely sure that it would open a popup either.

**Comment by Droyk** [comment]
that's sad.

**Comment by lopugit** [comment]
Oh man yeah this functionality would make this extension INCREDIBLE 🚀💯

I'll see what I can do 🧐

**Comment by fregante** [comment]
There's nothing to do, but Chrome now offers a native dropdown for this, which you can use if that's your intent (it's not an alternative to this extension unfortunately)

**Comment by lopugit** [comment]
> There's nothing to do, but Chrome now offers a native dropdown for this, which you can use if that's your intent (it's not an alternative to this extension unfortunately)

Doesn't offer quick search though 🙄
