### ISSUE TITLE
Add an option to enable only the last active extensions & way to save the current active extension list!

### ISSUE THREAD

**Issue by Droyk** [hankxdev/one-click-extensions-manager#74]
Since you already implemented the enable/disable all option. let's take it a step further, to make it more robust. 

Add an option to enable only the last active extensions.

You see Currently, it enables all or disables all. this feature isn't made for the users who have 80+ extensions & for them this feature is a nightmare. when you have 80+ extensions, not every extension is enabled & nor does the user remember how many are enabled. so if the user is troubleshooting to see what extension is making the trouble the user needs to make a screenshot to remember what extensions are enabled right now to save a lot of time in the future before hitting the disable all button, but sometimes this doesn't happen and now it's a very painful, time & energy consuming work to disable all the extension that the user currently doesn't want. so for this reason, "Enable only the last active extensions" should also be an option besides the "Enable ALL" on the top. I've also made a rough photoshop of it here 
![image](https://user-images.githubusercontent.com/15848350/131255576-0d7b897a-e591-4edd-87db-6eaa49aa7c6f.png)

It would also be pretty damn convenient if one can save the current session extension list and then make as many lists as one wants. let's say if I'm looking for a problematic extension. I immediately hit the disable button on the top. It saves the current session extension list (i.e. saves a list of extensions that were enabled at the time of hitting the disable all button!) and disables all the extensions. now I enable some extensions and let's say I have to do some other work. So I hit the disable button again & it automatically creates a new current session list and disables the extensions. When I come back I can just browse the saved lists in the extension manager to open the 1st list instead of the last one. It can look something like this 
![image](https://user-images.githubusercontent.com/15848350/131255590-ff5074da-6b45-4e3c-82e7-4ccacc225a53.png)

Look I know you want to keep it simple but it can still be a power toy for many users who just want this extension simple understandable user interface. if you don't want to show the session list option just give the users option to disable it. so both users can coexist! 
So please I request you to make this possible!

**Comment by fregante** [comment]
This already exists and it's the "undo" functionality. Unfortunately this only exists as long as the popup is open so if you close it you lose it. 

However you can open One Click's "options" page, which is the same page as the popup, but it will be open as a regular tab that can stay open as long as you want. 

Other filters and buttons won't be implemented, but you could open an issue about making the undo/redo functionality persist longer.

**Comment by Droyk** [comment]
I didn't think it properly. it would be better to have the functionality of "Enable the last active list"  what I want is better than the undo feature. & list feature kills two birds with one stone. if you implement this feature you don't need to add group functionality. just add the functionality to rename the lists and voila & it is also a saving feature!

>Other filters and buttons won't be implemented

Any specific reason for that? if it's about they don't look good well yes I'm a very bad designer you can change the looks as you please!

**Comment by fregante** [comment]
> add the functionality to rename the lists 

What's that?

**Comment by Droyk** [comment]
> > add the functionality to rename the lists
> 
> What's that?

the moment the user hit disable all it immediately makes & saves a current session list and saves it by date & time so the next time user wants to enable exactly the extensions that the user disabled at that date. they can and since the current session list save it by date and time if you can just add a way to rename them for eg. 01152233649 to productivity. you now made 2 ext's features.
One it made a Current session of anytime users disable any extension 2nd now your extension has a group feature by just adding a rename feature to the current session lists! 

![image](https://user-images.githubusercontent.com/15848350/149592114-29cd320a-fb3a-4479-ab74-1e627fc47d8b.png)
![image](https://user-images.githubusercontent.com/15848350/149592129-7ba101fd-bd48-43a1-bc55-8b946627d22f.png)

see the no 1 & 2 it means it can go to different sessions that I have created over a period of time!

**Comment by fregante** [comment]
However you call it (groups, lists, session) it's the same thing, and it's not going to be implemented, as suggested many times before. There are already other extensions that do this.
