### ISSUE TITLE
Better Dark mode theme that is easy on the eyes & looks good!

### ISSUE THREAD

**Issue by Droyk** [hankxdev/one-click-extensions-manager#75]
At present it looks like this 
![image](https://user-images.githubusercontent.com/15848350/131326351-4107b929-cee1-4ed4-9e79-b134c534ca01.png)

Well I tried to change it a liitle with added margin and instead of using uppercase I used Initial case but still doesn't look good.
![image](https://user-images.githubusercontent.com/15848350/131317961-4ffbac1a-8070-4ff3-a2de-4072254e42f6.png)

Well, take some inspiration from this extension 
https://github.com/luetage/extension_control
https://chrome.google.com/webstore/detail/extension-control/himccccaelhgphommckogopgpddngimf?hl=en-US 

In my office, everyone likes to use this because of its easy on the eyes UI. though the developer became too lazy doesn't seem to be adding new features to it. I would recommend ripping off the entire UI & making it yours. it's open-source anyway & you can just give it a credit in the description box that says the UI is inspired by this extension!

**Comment by Droyk** [comment]
Also, change that hideous scroll bar!

**Comment by fregante** [comment]
> the developer became too lazy doesn't seem to be adding new features to it

It's a free extension and it's not polite to call people lazy because they don't follow your advice. 

> I would recommend ripping off the entire UI & making it yours.

You can do that. This extension already works well as is, there are plenty more extensions you can pick from. 

> Also, change that hideous scroll bar!

That's the operating system's scroll bar. If you don't like it you can change OS.

> Well I tried to change it a liitle with added margin and instead of using uppercase I used Initial case but still doesn't look good.

It sounds like you don't like this extension. Please pick another extension that you like instead of asking to turn this extension into something that is not.

**Comment by Droyk** [comment]
Almost forgot about it! Finally had some time to reply! 
>You can do that. This extension already works well as is, there are plenty more extensions you can pick from.

Well, If I could I would've already done it! I'm not a programmer.
> That's the operating system's scroll bar. If you don't like it you can change OS.

![image](https://user-images.githubusercontent.com/15848350/149587548-8ad7fc92-9570-4367-921c-a78975022690.png)
I could show you countless examples of extensions changing their scrollbars so it matches UI & feels good to the eyes. 
there are plenty of examples out there. but since you're a dev. you're already knew about it so next time instead of saying other people to change OS'es why don't you update it? look it doesn't matter in the end it's your extension we can only suggest! 
> It sounds like you don't like this extension. Please pick another extension that you like instead of asking to turn this extension into something that is not.

I like the extension manager but if I like to make it better should I not suggest it? please tell me what I'm suggesting is so out of scope that this ext. manager can't be that! I find the top menu text doesn't match so I suggested changing it. I find the scroll bar hideous doesn't match the UI at all. so I said it but that doesn't mean I didn't like what other functionalities it's providing. that's the reason I came to GitHub to suggest it.  If you don't want to hear the suggestions you should mention that on your chrome extension page & readme page that says please don't suggest to me coz I know it all. & you're gonna waste your time so better don't suggest & the users won't!
