### ISSUE TITLE
Ability to pin extensions

### ISSUE THREAD

**Issue by rollingmoai** [hankxdev/one-click-extensions-manager#81]
As it says above, it would be great to pin extensions via this manager.

Maybe put it somewhere on the options on the right:
![image](https://user-images.githubusercontent.com/75471378/137701563-7e7ce071-c6db-41e0-8e69-193b2df5c466.png)

**Comment by WhiteNoiseDev** [comment]
I also miss the ability to pin.
If an extra icon is too much perhaps middle click (or ctrl/cmd click to pin) could be useful.

**Comment by DaneelReventelov** [comment]
+1

**Comment by gm-is** [comment]
nooboss remembers extension pin status.. it would be nice if you have it too

**Comment by fregante** [comment]
I just realized that "pinning" means something different in extensions. Unfortunately extensions cannot pin other extensions, so you must use the native manager for that.

<img width="122" alt="Screenshot" src="https://github.com/hankxdev/one-click-extensions-manager/assets/1402241/5658146d-4023-4c6f-826f-c9e920b59909">
