### ISSUE TITLE
Remove branch restrictions

### ISSUE THREAD

**Issue by fregante** [hankxdev/one-click-extensions-manager#90]
@hankxdev please remove the branch restrictions because it's impossible to get 2 reviews.

I'm pretty sure the restrictions also break the Publish workflow

**Comment by hankxdev** [comment]
just removed

**Comment by fregante** [comment]
Great! It seems that the release token is outdated. When you have 10 minutes, can you try generating a new one? I think I did it before, but now I don't have access to the options.

If you did it, then you can probably skip most steps:

https://github.com/fregante/chrome-webstore-upload/blob/main/How%20to%20generate%20Google%20API%20keys.md

**Comment by fregante** [comment]
It's an unrelated issue
