### ISSUE TITLE
Update automated-release token in settings

### ISSUE THREAD

**Issue by fregante** [hankxdev/one-click-extensions-manager#91]
See https://github.com/fregante/chrome-webstore-upload/blob/main/How%20to%20generate%20Google%20API%20keys.md

In https://github.com/hankxdev/one-click-extensions-manager/issues/90#issuecomment-1255840721

Log from https://github.com/hankxdev/one-click-extensions-manager/actions/runs/3110766643/jobs/5042297073

```
- Fetching token
{
Probably the provided refresh token is not valid. Try following the guide again
  "error": "invalid_grant",
https://github.com/fregante/chrome-webstore-upload/blob/main/How%20to%20generate%20Google%20API%20keys.md
  "error_description": "Bad Request"
}
{
  clientId: '***',
  refreshToken: '***'
}
```

**Comment by hankxdev** [comment]
@fregante I don't remember I removed your access from options. but let me create a new one.

**Comment by hankxdev** [comment]
```
{
  "error": {
    "code": 400,
    "message": "Publish condition not met: You must verify your contact email before you can publish any item. Begin the verification process on the Account tab.",
    "errors": [
      {
        "message": "Publish condition not met: You must verify your contact email before you can publish any item. Begin the verification process on the Account tab.",
        "domain": "chromewebstore.access",
        "reason": "badRequest"
      }
    ]
  }
```
keep getting this, however the email has been verified. will try later if there is no other issues.

**Comment by fregante** [comment]
I'll try uploading it manually, let's see what happens

**Comment by fregante** [comment]
I think it needed a privacy policy. It's now "pending"

I'll try triggering a new release later to see if the token works, and then I'll close this issue.

Side note: We were featured?! Since when?

<img width="544" alt="Screen Shot 14" src="https://user-images.githubusercontent.com/1402241/191908134-f4def79a-aefa-471b-a828-51269f9aba7d.png">

**Comment by hankxdev** [comment]
Not sure when. it's been featured automatically,

**Comment by fregante** [comment]
It worked!

<img width="938" alt="Screen Shot 1" src="https://user-images.githubusercontent.com/1402241/192133594-a2f7a052-25b4-4b9b-96fb-cdb89a152bb8.png">
